In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df=pd.read_csv("modified3.csv")

In [3]:
df

,product_name,price,rating,processor,Product_dimention in cm,Battery in mAh,Ram in GB,Rom in GB,Back_Camera in MP,Front_Camera in MP
0,"Redmi 8 (Onyx Black, 64 GB)",9499,4.4,Qualcomm Snapdragon 439 Processor,15.80,5000,4,64,12.00,8.0
1,"Realme 6 (Comet Blue, 128 GB)",16999,4.4,MediaTek Helio G90T Processor,16.51,4300,8,128,64.00,16.0
2,"Redmi 8 (Sapphire Blue, 64 GB)",9499,4.4,Qualcomm Snapdragon 439 Processor,15.80,5000,4,64,12.00,8.0
3,"Realme 6 Pro (Lightning Orange, 128 GB)",19999,4.4,Snapdragon 720G Processor,16.76,4300,8,128,64.00,16.0
4,"Asus ZenFone Max M1 (Black, 64 GB)",7499,4.5,Qualcomm Snapdragon 430 Processor,13.84,4000,4,64,13.00,8.0
...,...,...,...,...,...,...,...,...,...,...
343,Jivi R21Plus,869,4.0,MediaTek P22 Octa Core 2.0 GHz Processor,4.57,1000,1,16,0.03,0.0
344,"Realme C2 (Diamond Blue, 16 GB)",6499,4.4,Quad Core Processor,15.49,4000,2,16,13.00,5.0
345,"Meizu C9 Pro (Black, 32 GB)",6990,4.1,MTK6739 Processor,13.84,3000,3,32,13.00,5.0
346,"Lava Z91 (Blue, 32 GB)",8499,4.0,Qualcomm Snapdragon 730G Processor,14.48,3000,3,32,13.00,8.0
347,"OPPO Reno2 (Ocean Blue, 256 GB)",38990,4.5,"100 Days Replacement Warranty, 1 year warranty...",16.51,4000,8,256,48.00,16.0

In [4]:
x=df.iloc[:,[2,4,5,6,7,8,9]]
y=df.iloc[:,1]

In [5]:
x

,rating,Product_dimention in cm,Battery in mAh,Ram in GB,Rom in GB,Back_Camera in MP,Front_Camera in MP
0,4.4,15.80,5000,4,64,12.00,8.0
1,4.4,16.51,4300,8,128,64.00,16.0
2,4.4,15.80,5000,4,64,12.00,8.0
3,4.4,16.76,4300,8,128,64.00,16.0
4,4.5,13.84,4000,4,64,13.00,8.0
...,...,...,...,...,...,...,...
343,4.0,4.57,1000,1,16,0.03,0.0
344,4.4,15.49,4000,2,16,13.00,5.0
345,4.1,13.84,3000,3,32,13.00,5.0
346,4.0,14.48,3000,3,32,13.00,8.0
347,4.5,16.51,4000,8,256,48.00,16.0

In [6]:
y

0       9499
1      16999
2       9499
3      19999
4       7499
       ...
343      869
344     6499
345     6990
346     8499
347    38990
Name: price, Length: 348, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

In [8]:
from sklearn.linear_model import LinearRegression
classifier=LinearRegression()
classifier.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [9]:
y_pred=classifier.predict(x_test)
y_pred

array([ 9843.78001226, 18581.4647942 , 10988.50615321, 25998.47504784,
        5193.69326477, 19982.38907178, 23207.9696609 , 12529.19606967,
        7355.68854774, 44823.71025068, 13737.82855323, 25427.73884427,
       20593.42049722,  7100.84528003, 30678.24680063,  8356.88673654,
       16498.10725993, 12514.44783401, 18275.84656951, 28042.88309933,
       11242.25469431, 18242.8120052 , 13130.44837256, 19265.84070845,
       19116.18850646, 39322.57854251, 10350.2768633 , 12317.6357859 ,
       20764.49956842, 27660.72336053, 18581.4647942 , 25955.4227436 ,
       25715.55314406, 12239.95521935, 23018.79490168, 27674.55449816,
        9571.17940321, 23816.19421554, 15476.38874996, 22774.94678201,
       19619.31960231,  8860.25902477, 11209.23561214, 11107.53011872,
       -4951.93939055, 18692.30599957, 19753.22424434, 20231.28791836,
       31365.23407564, 27249.45731965, 45995.42177125, 44635.77735924,
       10683.7202966 ,  9843.78001226, 14036.8401093 , 24125.33691827,
       19813.96968323, 45131.0944261 , 27240.62523409, 26416.64387502,
       11107.53011872, 10922.4682577 , 10949.19680964, 12921.60955836,
       14938.24967392, 14653.78093921, 22738.03312191, 12493.79968815,
       29836.93780748, 19714.48191663])

In [13]:
from sklearn.metrics import r2_score
score=r2_score(y_test,y_pred)

In [14]:
score

0.3556396492776881